<?hh

use Facebook\HackRouter\{
  HttpMethod,
  NotFoundException
};

class Request {

  public function __construct(public $controller) {
  }

  public function getController(): string {
    return get_class($this->controller);
  }

  public static function get(): Request {
    $router = new Router();
    $path = $_SERVER['REQUEST_URI'];
    try {
      // Attmept to match the path with the autogenerated router
      list($controller_name, $_) = $router->routeRequest(HttpMethod::GET, $path);
      $controller = new $controller_name();
    } catch (NotFoundException $e) {
       $controller = new NotFoundController();
    }
    return new Request($controller);
  }
}
